export default {
  "2020-12-03": {
    Medway: 2
  },
  "2020-12-06": {
    Medway: 1,
    "Stoke-on-Trent": 1,
    "Blackburn with Darwen": 1,
    Bury: 1,
    Dudley: 1,
    "Kingston upon Hull, City of": 1,
    Doncaster: 1,
    Rochdale: 1,
    Calderdale: 1,
    Bradford: 1,
    Walsall: 1,
    Kirklees: 1,
    Rotherham: 1,
    Bolton: 1,
    Wakefield: 1,
    "Stockton-on-Tees": 1,
    Northumberland: 1,
    "North Tyneside": 1,
    Leeds: 1,
    "East Riding of Yorkshire": 1,
    Sheffield: 1,
    Barnsley: 1,
    "North East Lincolnshire": 1,
    "Bristol, City of": 1,
    "Newcastle upon Tyne": 1,
    Tameside: 1,
    Gateshead: 1
  },
  "2020-12-07": {
    Havering: 1,
    "Waltham Forest": 1,
    "Barking and Dagenham": 1,
    Redbridge: 1,
    Thurrock: 1,
    Newham: 1,
    Luton: 1,
    Enfield: 1,
    Bexley: 1,
    "Southend-on-Sea": 1,
    "Tower Hamlets": 1,
    "Kingston upon Thames": 1,
    Harrow: 1,
    Greenwich: 1,
    Merton: 1,
    Peterborough: 1,
    Haringey: 1,
    "Hackney and City of London": 1,
    Bromley: 1,
    "Milton Keynes": 1,
    Sutton: 1,
    Hillingdon: 1,
    Reading: 1,
    "Bracknell Forest": 1,
    Croydon: 1,
    Barnet: 1,
    Brent: 1,
    Hounslow: 1,
    Ealing: 1,
    Portsmouth: 1,
    Wokingham: 1,
    "Central Bedfordshire": 1,
    Lewisham: 1,
    Southwark: 1,
    Bedford: 1,
    Wandsworth: 1,
    Lambeth: 1,
    Islington: 1,
    "Kensington and Chelsea": 1,
    Warrington: 1,
    "Hammersmith and Fulham": 1,
    Halton: 1,
    Camden: 1,
    "St. Helens": 1,
    Rutland: 1,
    "West Berkshire": 1
  },
  "2020-12-16": {
    Thurrock: 2,
    Havering: 1,
    Redbridge: 1,
    "Barking and Dagenham": 1,
    Bexley: 1,
    Enfield: 1,
    "Waltham Forest": 2,
    Newham: 1,
    "Tower Hamlets": 1,
    "Southend-on-Sea": 1,
    Haringey: 1,
    Bromley: 1,
    "Hackney and City of London": 1,
    Harrow: 1,
    "Kingston upon Thames": 1,
    Croydon: 1,
    Greenwich: 1,
    Merton: 1,
    Sutton: 1,
    Lewisham: 1,
    Lambeth: 1,
    Wandsworth: 2,
    Hillingdon: 1,
    Islington: 1,
    Barnet: 1,
    Southwark: 1,
    Brent: 1,
    Hounslow: 1,
    Ealing: 1,
    "Hammersmith and Fulham": 1,
    "Richmond upon Thames": 1,
    "Kensington and Chelsea": 1,
    Camden: 2,
    Westminster: 1
  },
  "2020-12-19": {
    "Milton Keynes": 2,
    Luton: 1,
    Reading: 1,
    "Bracknell Forest": 1,
    Bedford: 2,
    "Central Bedfordshire": 1,
    Peterborough: 1,
    Portsmouth: 1,
    Wokingham: 1,
    "Windsor and Maidenhead": 2,
    "West Berkshire": 1,
    Calderdale: 1,
    "Bristol, City of": 2,
    "North Somerset": 2
  },
  "2020-12-20": {
    "Milton Keynes": 2,
    Luton: 1,
    Bedford: 2,
    "Bracknell Forest": 1,
    Reading: 1,
    "Central Bedfordshire": 1,
    Peterborough: 1,
    Portsmouth: 2,
    "Windsor and Maidenhead": 1,
    Wokingham: 1,
    "West Berkshire": 1
  },
  "2020-12-21": {
    Thurrock: 1,
    Havering: 1,
    Redbridge: 1,
    "Southend-on-Sea": 1,
    "Barking and Dagenham": 1,
    Bexley: 1,
    "Tower Hamlets": 1,
    "Waltham Forest": 1,
    Enfield: 1,
    Newham: 1,
    "Milton Keynes": 1,
    Bromley: 1,
    "Hackney and City of London": 1,
    Haringey: 1,
    Merton: 1,
    Wandsworth: 1,
    Lambeth: 1,
    Greenwich: 1,
    Croydon: 1,
    Southwark: 1,
    Sutton: 1,
    Barnet: 1,
    Hillingdon: 1,
    Lewisham: 1,
    Hounslow: 1,
    Harrow: 1,
    Islington: 1,
    "Hammersmith and Fulham": 1,
    Brent: 1,
    "Kingston upon Thames": 1,
    Ealing: 1,
    "Richmond upon Thames": 1,
    Luton: 1,
    Bedford: 1,
    "Bracknell Forest": 1,
    "Kensington and Chelsea": 1,
    "Central Bedfordshire": 1,
    Camden: 1,
    Westminster: 1,
    Reading: 1,
    "Windsor and Maidenhead": 1,
    Portsmouth: 1,
    Peterborough: 1,
    Wokingham: 1,
    "West Berkshire": 1
  },
  "2020-12-22": {
    Medway: 1,
    Slough: 1,
    Hartlepool: 1,
    Wolverhampton: 1,
    "Blackburn with Darwen": 1,
    Sandwell: 1,
    Birmingham: 1,
    Leicester: 1,
    "Stoke-on-Trent": 1,
    Walsall: 1,
    Dudley: 1,
    "Kingston upon Hull, City of": 1,
    Derby: 1,
    Coventry: 1,
    Solihull: 1,
    "Stockton-on-Tees": 1,
    "County Durham": 1,
    "South Tyneside": 1,
    Nottingham: 1,
    Middlesbrough: 1,
    Darlington: 1,
    Bury: 1,
    Trafford: 1,
    Doncaster: 1,
    Rotherham: 1,
    Salford: 1,
    Rochdale: 1,
    Barnsley: 1,
    Manchester: 1,
    Gateshead: 1,
    "North Lincolnshire": 1,
    Stockport: 1,
    Northumberland: 1,
    Sunderland: 1,
    Oldham: 1,
    Wakefield: 1,
    "South Gloucestershire": 1,
    "East Riding of Yorkshire": 1,
    Leeds: 1,
    Kirklees: 1,
    Bradford: 1,
    Wigan: 1,
    Sheffield: 1,
    Calderdale: 1,
    Blackpool: 1,
    Tameside: 1,
    Bolton: 1,
    "North Tyneside": 1,
    "Newcastle upon Tyne": 1,
    "Redcar and Cleveland": 1,
    "North East Lincolnshire": 1,
    "North Somerset": 1,
    "Bristol, City of": 1
  },
  "2020-12-26": {
    Haringey: 1,
    "Brighton and Hove": 1,
    Southampton: 1,
    Warrington: 1,
    Swindon: 1,
    "Cheshire East": 1,
    "North Somerset": 1,
    "Isle of Wight": 1,
    "Bristol, City of": 1,
    Oxfordshire: 2
  },
  "2020-12-31": {
    Harrow: 1,
    Hartlepool: 1,
    Wolverhampton: 1,
    "Isle of Wight": 1,
    Sandwell: 1,
    "Blackburn with Darwen": 1,
    Walsall: 1,
    Birmingham: 1,
    Warrington: 1,
    Dudley: 1,
    Swindon: 1,
    Derby: 1,
    "Cheshire West and Chester": 1,
    "South Tyneside": 1,
    Sunderland: 1,
    Leicester: 1,
    Middlesbrough: 1,
    "County Durham": 1,
    Solihull: 1,
    "Cheshire East": 1,
    Gateshead: 1,
    Coventry: 1,
    "Stockton-on-Tees": 1,
    Darlington: 1,
    Trafford: 1,
    Nottingham: 1,
    Wigan: 1,
    Bury: 1,
    Northumberland: 1,
    Stockport: 1,
    "Stoke-on-Trent": 1,
    Manchester: 1,
    "Redcar and Cleveland": 1,
    Rochdale: 1,
    Salford: 1,
    Oldham: 1,
    Tameside: 1,
    Blackpool: 1,
    Bolton: 1,
    "North Tyneside": 1,
    "North Lincolnshire": 1,
    "Newcastle upon Tyne": 1,
    "North East Lincolnshire": 1
  }
};
